on "test" => sub {
    requires "ExtUtils::MakeMaker" => 0;
    requires "File::Spec" => 0;
    requires "File::Temp" => 0;
    requires "Test::More" => 0;   
};

requires "Encode" => 0;
requires "No::Worries" => "1.4";
requires "POSIX" => 0;
requires "Time::HiRes" => 0;